# Generated by Django 4.1.2 on 2023-01-04 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_full_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(db_index=True, max_length=10, unique=True)),
                ('user_email', models.EmailField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)])),
                ('user_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)])),
                ('user_slug', models.SlugField(default='djangodbmodelsfieldscharfield', editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('loan_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('request_date_time', models.DateTimeField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=11)),
                ('num_of_payments', models.IntegerField()),
                ('rate_per_period', models.DecimalField(decimal_places=3, max_digits=4)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=11)),
                ('is_approved', models.BooleanField(default=False)),
                ('user_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_user.usermodel')),
            ],
        ),
    ]
