# Generated by Django 4.1.2 on 2023-01-05 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_user', '0002_remove_usermodel_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanmodel',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanmodel',
            name='request_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='loanmodel',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanmodel',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
