# Generated by Django 4.1.2 on 2023-01-05 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_email', models.EmailField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('admin_password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
